name: IRIS BUILD

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "--enable-native-access=ALL-UNNAMED"
    steps:
      - uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Configure Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "Github Actions"



      - name: Build and Copy to Out
        run: ./gradlew buildAll buildAllToOut

      - uses: actions/upload-artifact@v4
        with:
          name: "IRIS"
          path: "build/libs/*.jar"
